language: node_js
node_js:
- '4.2'
before_script:
- npm install -g bower karma grunt-cli jshint
- npm install
- bower install
script:
- grunt build
deploy:
  - provider: s3
    bucket: "excel.danielcottone.com"
    endpoint: "excel.danielcottone.com.s3-website-us-east-1.amazonaws.com"
    region: "us-east-1"
    skip_cleanup: true
    acl: public_read
    access_key_id:
      secure: "fDhUz3J+NmnF/K/MEkFSz8DJOLmpwUf9XY4wVvQe9jJFg6CPHen7t6C1t8qfkL/VzNZFvsPcSEzJKmDIPo6EgoUFvK+SdOdbSZgi3Cd8dVlz3ACTyvF62mhM/6fS3hcKMCZ6Q5yfTiU0Mhj3jcwzRoEI0A/roCSgqJGgr8IIaLnlkgWs39VhW3ez8J2uMTQKWDOuM+l4Mo4IQc4TNBgNqpDxYlfTs5yIrLlX+O0TJ5mTRdJp02bzScb6lVUsABTBhGU796M7TWPO59Spp1g19c01YcHSOxXoETyxJ9DMMTO4x7/B0czQYkBCboUJpDExRBhLgZEC+69i3GCPiQKeanuXMlSwU5jngYVLthLIuBQWOOY+l+Yz4OKvjxKs83J3WuowD0uPRR7cztrhFsrg3x2o1lGtR7epP6gTXPPEMI8cPPgWUqkXYeX2T7B6FXnxYmxPBxaUcSbWoZZkplqiWgWr5cB89r8fEs5hAMukcv68pttmGswdrKShCydiHbpY+jtmVKoAJOdKA+Q8wRKE1PhAhTAUVlvsn++ol1aG7zsumoZiPgj2IcFqKk844VUS4aMkex3j8u3IBpQg5eVqufDRiSI2WaGKyG1LSKJg66y4oFxF+woFY8Py2Gvsg+ABDG+0PG3pAlprs3rzh4tE0wkemjx/3cbzCNgnu/aMZFo="
    secret_access_key:
      secure: "Ii60d8g06eH8hGJFR2HMvGyK7ELogYeBhDFlw37zY6b9AOEazR7xbTRdxWpl+0BciB3EqnMe4pwu0rOTy5SjT74CF3AAeNu6vGo4M8Q5sO/4GjgJhNlz+SN92Jmrdpgn34e+X7k5oybF806iPWH0C1ILV3pbOOw+JHx00sUGaVDvVqrY3CJSch87le8rpgn0w+yRfqZMjGt/N+IjN1oJPj9xiVOIiP/k7BubnXnTkRP4vHL1Cu3hyCK4TL8EIoY1VFVfijdHEjywZLHFGlbP5UeS8jR+9vvKCpeftZLoZPTQCFHpyzqb6uIMaYLzU26+0R2OCmtv25TW9gGIMXqz+t/V2TB0V9BuElFjk+FeRGu/TTW5BBKMiWuZgtogPbS3Wc0LT902DEoMe1Jw6oDe8gUoTTLobwISRmBCbxwWmzGUxLwdtvXOFezaY7bqTLQCMGk/p7cjBhBM6uFW6O103wMquFcBM3SDwd7fvq2IfW+EDCi0A+c0ir8LZ/Q64GKlUvizp+nV6onUKGmEZCihEhhrcVFdcOf8yRYYcNREXM7gzSbSjTurmU6qPq+8OQZKdzZIoJ3OROHK1quYM4V5QjuCvht0TW7WHI3tCoHSRr0EbXgPohgwvNqbGImbmm/KhfcyPORfEgSPQON37VewxDwJr38aY3+E5NpaNhsyttU="
    local-dir: dist
    on:
      branch: master
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe80e2e3dd3fd8564be9
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
